# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c20b992c2578e4ffdc779b5620efc2a316c472dbf4c0067b4d7e609874cbd8082b7f9a27695d46ca929498d22983613f750c771fc29688302286f8758288934

test:
  secret_key_base: 638843c84ea2ee2719092be99e6abde7026c90f5b85a5796310c72da6a57f3f2bfe0d7a683918850f9e1a2bbe5eb172d133759bd2c37663faf89334e6d81078d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
